GET http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ltb25lIiwiaWF0IjoxNjU4OTA4MDMzLCJleHAiOjE2NTg5MDgwOTN9.M0ZhJtKw0OsQtSUGs3QgR2IQbbghuCA9-r02S47t8l0

###

POST  http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "username":"Simone"
}

###

POST  http://localhost:4000/api/v1/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ltb25lIiwiaWF0IjoxNjU4OTA4MDIxfQ.g4n-bBbyCaVJPTnkcMdFt8JkMrQ_js4iwUuu0JYG0ig"
}

###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name":"Simone",
    "email":"simone.sanfilippo@diemmea.com",
    "password":"password"
}