GET http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ltb25lIiwiaWF0IjoxNjYwNjY5NjIyLCJleHAiOjE2NjA2Njk2ODJ9.HL9k8Dv-UOF6mkPDDSowfUH6_tbgBobRKQtXKDv3qd4

###

POST  http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "username":"Simone"
}

###

POST  http://localhost:4000/api/v1/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2ltb25lIiwiaWF0IjoxNjYwNjY5ODQxfQ.olP2LWxg8uv2_wFshtpjsh4LMTjOnv0-UZJQq_JflG4"
}

###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "name":"Simone",
    "email":"simone.sanfilippo@diemmea.com",
    "password":"password"
}